### ISSUE TITLE
How to Capture No DXCC information?

### ISSUE THREAD

**Issue by zmd94** [schrockwell/dx-lookup#1]
Hi, my friend.

First of all, thank you for wonderful gem. I'm using this with one of my project. It is working well.

However, when I try to search for invalid callsign, it return bellow errors:

```ruby
app/controllers/dashboard_controller.rb:85:in `export'
Started GET "/export" for 127.0.0.1 at 2018-09-30 14:36:09 +0800
Processing by DashboardController#export as HTML
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDE
R BY "users"."id" ASC LIMIT $2  [["id", 7], ["LIMIT", 1]]
  ? app/controllers/application_controller.rb:14
Completed 500 Internal Server Error in 1237ms (ActiveRecord: 4.8ms)


Sending event 8fc59e223e984ae18d20a9e82c649023 to Sentry
Unable to record event with remote Sentry server (Raven::Error - the server resp
onded with status 400 Error in headers is: Invalid project_id: u'1261764'):
C:/Ruby/lib/ruby/gems/2.5.0/gems/sentry-raven-2.7.4/lib/raven/transports/http.rb
:34:in `rescue in send_event'
C:/Ruby/lib/ruby/gems/2.5.0/gems/sentry-raven-2.7.4/lib/raven/transports/http.rb
:16:in `send_event'
C:/Ruby/lib/ruby/gems/2.5.0/gems/sentry-raven-2.7.4/lib/raven/client.rb:37:in `s
end_event'
C:/Ruby/lib/ruby/gems/2.5.0/gems/sentry-raven-2.7.4/lib/raven/instance.rb:81:in
`send_event'
C:/Ruby/lib/ruby/gems/2.5.0/gems/sentry-raven-2.7.4/lib/raven/instance.rb:126:in
 `capture_type'
C:/Ruby/lib/ruby/gems/2.5.0/gems/sentry-raven-2.7.4/lib/raven/integrations/rack.
rb:28:in `capture_type'
C:/Ruby/lib/ruby/gems/2.5.0/gems/sentry-raven-2.7.4/lib/raven/integrations/rails
/overrides/debug_exceptions_catcher.rb:8:in `render_exception'
C:/Ruby/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware
/debug_exceptions.rb:71:in `rescue in call'
C:/Ruby/lib/ruby/gems/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware
/debug_exceptions.rb:59:in `call'
C:/Ruby/lib/ruby/gems/2.5.0/gems/newrelic_rpm-5.3.0.346/lib/new_relic/agent/inst
rumentation/middleware_tracing.rb:92:in `call'
C:/Ruby/lib/ruby/gems/2.5.0/gems/web-console-3.6.2/lib/web_console/middleware.rb
:135:in `call_app'
Failed to submit event: DX::Lookup::QRZ::APIError: No DXCC information for: 92WP
Z

DX::Lookup::QRZ::APIError (No DXCC information for: 92WPZ):

app/controllers/dashboard_controller.rb:85:in `export'
```
So, how we can catch invalid callsign errors?

Below is the code in my dashboard_controller.rb:

```ruby
  def export

    qrz = DX::Lookup::QRZ.new(ENV['QRZ_USERNAME'], ENV['QRZ_PASSWORD'])
    @entity = qrz.get_callsign_entity('92WPZ')
	
    redirect_to dashboard_path, notice: "#{@entity.name.upcase}"
	
  end  
```

Thank you. Greeting from Malaysia.

- 9W2ZOW.

**Comment by zmd94** [comment]
Alright, nevermind. Already find the method to fix it. Just use `begin` and `rescue` block.

Below code will handle the error:

```ruby
  def export

    qrz = DX::Lookup::QRZ.new(ENV['QRZ_USERNAME'], ENV['QRZ_PASSWORD'])
    
    begin
      @entity = qrz.get_callsign_entity('92WPZ')
      redirect_to dashboard_path, notice: "#{@entity.name.upcase}"
    rescue DX::Lookup::QRZ::APIError
      redirect_to dashboard_path, notice: "QRZ Error!"
    end

  end  
```
By the way, you should update the ReadMe section regarding on how to handle the `DX::Lookup::QRZ::APIError`.

Regards,
- 9W2ZOW.
